SELECT c.NAME, COUNT(p.ID) AS PROJECT_COUNT
FROM client c
JOIN project p ON c.ID = p.CLIENT_ID
GROUP BY c.NAME
HAVING PROJECT_COUNT = (
    SELECT MAX(PROJECT_COUNT)
    FROM (SELECT COUNT(ID) AS PROJECT_COUNT FROM project GROUP BY CLIENT_ID) AS counts
);
