SELECT p.ID,
       DATEDIFF('DAY', p.START_DATE, p.FINISH_DATE) AS MONTH_COUNT
FROM project p
WHERE DATEDIFF('DAY', p.START_DATE, p.FINISH_DATE) = (
    SELECT MAX(DATEDIFF('DAY', START_DATE, FINISH_DATE)) FROM project
    );
